MACRO(HEADER_DIRECTORIES return_list)
    FILE(GLOB_RECURSE new_list *.h)
    SET(dir_list "")
    FOREACH(file_path ${new_list})
        GET_FILENAME_COMPONENT(dir_path ${file_path} PATH)
        SET(dir_list ${dir_list} ${dir_path})
    ENDFOREACH()
    LIST(REMOVE_DUPLICATES dir_list)
    SET(${return_list} ${dir_list})
ENDMACRO()

MACRO(EXECUTABLE_FILES return_list search_dir_list)
        SET(dir_list "")
        FOREACH(search_dir ${search_dir_list})
            FILE(GLOB_RECURSE new_list ${search_dir}/*.c*)
            FOREACH(file_path ${new_list})
                 SET(dir_list ${dir_list} ${file_path})
            ENDFOREACH()
        ENDFOREACH()
       
        SET(${return_list} ${dir_list})
ENDMACRO()

HEADER_DIRECTORIES(header_dir_list)

message(STATUS "[HEADER_DIRECTORIES] ${header_dir_list}")
list(LENGTH header_dir_list header_dir_list_count)
message(STATUS "[INFO] Found ${header_dir_list_count} header directories.")

EXECUTABLE_FILES(list_executables "${list_executables}")